export const ApiUrl="http://localhost:200/admin"
export const ApiUrlCategory="http://localhost:200/category"
export const ApiUrlSubCategory="http://localhost:200/subcategory"
export const ApiUrlProduct="http://localhost:200/product"
export const PublicImgUrl="http://localhost:3000/image/"